### ISSUE TITLE
Нет сессии в куках

### ISSUE THREAD

**Issue by tgrx** [Mitya890625/FILMSREVIEW#8]
Привет, вижу что в CI не проходит тест, т.к. нет `sessionid` в куках

<img width="453" alt="image" src="https://github.com/Mitya890625/FILMSREVIEW/assets/3865736/9b646d59-dedc-4bbf-bb9c-5e1184330f1d">

**Comment by Mitya890625** [comment]
Куки нету потому что не регается юзер, пробую зарегистрировать юзера через httpx - нету куки `sessionid `, а когда руками делаю - появляется. В случае с логином на существующего юзера все нормально, в двух словах - через питон не регается юзер.
![1](https://github.com/Mitya890625/FILMSREVIEW/assets/57485444/c5b78989-a831-401c-9130-18cbf0729922)

**Comment by Mitya890625** [comment]
done
